const WEBHOOK_EVENTS = {
  OFFER_TX_STATUS_UPDATED: "OFFER_TRANSACTION_STATUS_UPDATED",
  DISPUTE_COMPLETED: "OFFER_TRANSACTION_DISPUTE_STATUS_UPDATED",
  ORDER_STATUS_UPDATED: "BNPL_ORDER_STATUS_UPDATED",
  DISBURSEMENT_STATUS_UPDATED: "BNPL_DISBURSEMENT_REQUIREMENT_STATUS_UPDATED"
}

const BNPL_ORDER_STATUS = {
  ORDER_STATUS_PENDING: "PENDING",
  ORDER_STATUS_APPROVED: "APPROVED",
  ORDER_STATUS_CANCELED: "CANCELED",
  ORDER_STATUS_CANCELING: "CANCELING",
  ORDER_STATUS_DISBURSING: "DISBURSING",
  ORDER_STATUS_PAID: "PAID",
};

module.exports = {
  BNPL_ORDER_STATUS,
  WEBHOOK_EVENTS
}
